###############################################################################
# HomeAssistant 1.3 – Battery Automations (Task 23, Phase 1)
###############################################################################

automation:

  # ---------------------------------------------------------------------------
  # 1) Min SOC protection (normal) – log when we drop below normal minimum
  # ---------------------------------------------------------------------------
  - id: ha1_battery_min_soc_normal_notice
    alias: "HA1 – Battery: SOC below normal minimum"
    mode: single
    trigger:
      - alias: "Battery SOC below normal minimum"
        platform: template
        value_template: >
          {{ states('sensor.ha1_huawei_battery_soc') | float(0) <
             states('input_number.ha1_battery_min_soc_normal') | float(20) }}
    condition:
      - condition: state
        entity_id: input_boolean.ha1_automations_master_enable
        state: "on"
      - condition: state
        entity_id: input_boolean.ha1_battery_automation_enabled
        state: "on"
      # Optional safety: respect debug freeze if you have it
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.ha1_debug_freeze_optimizers
            state: "off"
          - condition: template
            value_template: "{{ states('input_boolean.ha1_debug_freeze_optimizers') in ['unknown','unavailable'] }}"
    action:
      - service: logbook.log
        data:
          name: "HA1 Battery"
          message: >
            Battery SOC {{ states('sensor.ha1_huawei_battery_soc') | float(0) | round(1) }}%
            is below normal minimum
            ({{ states('input_number.ha1_battery_min_soc_normal') | float(0) | round(1) }}%).
            Battery should not be used for non-essential optimizations.
          entity_id: sensor.ha1_huawei_battery_soc

  # ---------------------------------------------------------------------------
  # 2) Min SOC protection (peak mode) – log when peak reserve is hit
  # ---------------------------------------------------------------------------
  - id: ha1_battery_min_soc_peak_notice
    alias: "HA1 – Battery: SOC below peak minimum (peak shaving)"
    mode: single
    trigger:
      - alias: "Battery SOC below peak minimum"
        platform: template
        value_template: >
          {{ states('sensor.ha1_huawei_battery_soc') | float(0) <
             states('input_number.ha1_battery_min_soc_peak') | float(30) }}
    condition:
      - condition: state
        entity_id: input_boolean.ha1_automations_master_enable
        state: "on"
      - condition: state
        entity_id: input_boolean.ha1_battery_automation_enabled
        state: "on"
      - condition: state
        entity_id: input_boolean.ha1_peak_shaving_enabled
        state: "on"
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.ha1_debug_freeze_optimizers
            state: "off"
          - condition: template
            value_template: "{{ states('input_boolean.ha1_debug_freeze_optimizers') in ['unknown','unavailable'] }}"
    action:
      - service: logbook.log
        data:
          name: "HA1 Battery"
          message: >
            Battery SOC {{ states('sensor.ha1_huawei_battery_soc') | float(0) | round(1) }}%
            is below peak minimum
            ({{ states('input_number.ha1_battery_min_soc_peak') | float(0) | round(1) }}%).
            Battery should no longer be used for peak shaving.
          entity_id: sensor.ha1_huawei_battery_soc

  # ---------------------------------------------------------------------------
  # 3) Grid charge toggle – react when allow_grid_charge boolean changes
  # ---------------------------------------------------------------------------
  - id: ha1_battery_grid_charge_toggle
    alias: "HA1 – Battery: grid charge allow/deny handler"
    mode: single
    trigger:
      - platform: state
        entity_id: input_boolean.ha1_battery_allow_grid_charge
    condition:
      - condition: state
        entity_id: input_boolean.ha1_automations_master_enable
        state: "on"
      - condition: state
        entity_id: input_boolean.ha1_battery_automation_enabled
        state: "on"
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.ha1_debug_freeze_optimizers
            state: "off"
          - condition: template
            value_template: "{{ states('input_boolean.ha1_debug_freeze_optimizers') in ['unknown','unavailable'] }}"
    action:
      - choose:
          # Allow grid charge turned ON
          - conditions:
              - condition: state
                entity_id: input_boolean.ha1_battery_allow_grid_charge
                state: "on"
            sequence:
              - service: script.ha1_battery_allow_grid_charge_on
              - service: script.ha1_battery_apply_grid_charge_limit
              - service: logbook.log
                data:
                  name: "HA1 Battery"
                  message: >
                    Grid charging enabled via helper; grid charge limit applied.
                  entity_id: input_boolean.ha1_battery_allow_grid_charge

          # Allow grid charge turned OFF
          - conditions:
              - condition: state
                entity_id: input_boolean.ha1_battery_allow_grid_charge
                state: "off"
            sequence:
              - service: script.ha1_battery_allow_grid_charge_off
              - service: logbook.log
                data:
                  name: "HA1 Battery"
                  message: "Grid charging disabled via helper."
                  entity_id: input_boolean.ha1_battery_allow_grid_charge
        default: []

  # ---------------------------------------------------------------------------
  # 4) Grid charge stop – when target SOC reached (max_soc_charging)
  # ---------------------------------------------------------------------------
  - id: ha1_battery_grid_charge_stop_at_target
    alias: "HA1 – Battery: stop grid charge at target SOC"
    mode: single
    trigger:
      - alias: "Battery SOC reached or exceeded max charging target"
        platform: template
        value_template: >
          {{ states('sensor.ha1_huawei_battery_soc') | float(0) >=
             states('input_number.ha1_battery_max_soc_charging') | float(80) }}
    condition:
      - condition: state
        entity_id: input_boolean.ha1_automations_master_enable
        state: "on"
      - condition: state
        entity_id: input_boolean.ha1_battery_automation_enabled
        state: "on"
      - condition: state
        entity_id: input_boolean.ha1_battery_allow_grid_charge
        state: "on"
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.ha1_debug_freeze_optimizers
            state: "off"
          - condition: template
            value_template: "{{ states('input_boolean.ha1_debug_freeze_optimizers') in ['unknown','unavailable'] }}"
    action:
      - service: script.ha1_battery_allow_grid_charge_off
      - service: logbook.log
        data:
          name: "HA1 Battery"
          message: >
            Grid charging stopped: SOC
            {{ states('sensor.ha1_huawei_battery_soc') | float(0) | round(1) }}%
            reached or exceeded target
            ({{ states('input_number.ha1_battery_max_soc_charging') | float(0) | round(1) }}%).
          entity_id: sensor.ha1_huawei_battery_soc

  # ---------------------------------------------------------------------------
  # 5) No-export-while-battery-needs-charge – observability only (Phase 1)
  # ---------------------------------------------------------------------------
  - id: ha1_battery_no_export_while_needs_charge_notice
    alias: "HA1 – Battery: export while battery needs charge (notice)"
    mode: single
    trigger:
      - alias: "Periodic check for export while SOC below target"
        platform: time_pattern
        minutes: "/5"
    condition:
      - condition: state
        entity_id: input_boolean.ha1_automations_master_enable
        state: "on"
      - condition: state
        entity_id: input_boolean.ha1_battery_automation_enabled
        state: "on"
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.ha1_debug_freeze_optimizers
            state: "off"
          - condition: template
            value_template: "{{ states('input_boolean.ha1_debug_freeze_optimizers') in ['unknown','unavailable'] }}"
      # Battery still needs charge (below export target SOC)
      - condition: template
        value_template: >
          {{ states('sensor.ha1_huawei_battery_soc') | float(0) <
             states('input_number.ha1_battery_max_soc_charging') | float(80) }}
      # Export is happening: either solar-to-grid flow OR net grid export
      - condition: or
        conditions:
          - condition: template
            value_template: >
              {{ states('sensor.ha1_flow_solar_to_grid') | float(0) > 300 }}
          - condition: template
            value_template: >
              {{ states('sensor.ha1_net_grid_power') | float(0) < -300 }}
    action:
      - service: logbook.log
        data:
          name: "HA1 Battery"
          message: >
            Export detected while battery SOC
            ({{ states('sensor.ha1_huawei_battery_soc') | float(0) | round(1) }}%)
            is below export target
            ({{ states('input_number.ha1_battery_max_soc_charging') | float(0) | round(1) }}%).
            Future export strategies should prefer charging the battery first.
          entity_id: sensor.ha1_flow_solar_to_grid
