# packages/energy_automations_core_1_3.yaml
#
# Task 20 – Core automation scaffolding for HA 1.3 energy logic.
# Focus: peak shaving, battery behavior, and EV charging control.
# Automations primarily log and raise debug flags so the flows can be tuned
# before enabling real control actions.

automation:
  - id: ha1_peak_guard_flag_v13
    alias: "HA1 1.3 – Peak guard scaffold"
    description: "Task 20 – Flag/log peak events when billable load nears or exceeds the configured warning/limit."
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.ha1_peak_billable_power_kw
    condition:
      - condition: state
        entity_id: input_boolean.ha1_automations_master_enable
        state: 'on'
      - condition: state
        entity_id: input_boolean.ha1_peak_shaving_enabled
        state: 'on'
      - condition: state
        entity_id: input_boolean.ha1_debug_freeze_optimizers
        state: 'off'
      - condition: template
        value_template: >-
          {{ states('sensor.ha1_peak_billable_power_kw') not in ['unknown', 'unavailable', ''] }}
    action:
      - variables:
          load_kw: "{{ states('sensor.ha1_peak_billable_power_kw') | float(0) }}"
          limit_kw: "{{ states('input_number.ha1_peak_limit_kw') | float(0) }}"
          warning_kw: >-
            {% set warn = states('input_number.ha1_peak_warning_kw') | float(0) %}
            {% if warn > 0 %}
              {{ warn }}
            {% else %}
              {{ states('input_number.ha1_peak_limit_kw') | float(0) }}
            {% endif %}
          margin_kw: "{{ states('sensor.ha1_peak_margin_kw') | float(0) }}"
          flag_on: "{{ is_state('input_boolean.ha1_flag_peak_event_active', 'on') }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ warning_kw > 0 and load_kw >= warning_kw }}"
            sequence:
              - condition: template
                value_template: "{{ not flag_on }}"
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.ha1_flag_peak_event_active
              - service: logbook.log
                data:
                  name: "HA1 Peak Guard"
                  message: >-
                    Task 20: Peak event flagged – {{ load_kw | round(2) }} kW vs warning {{ warning_kw | round(2) }} kW (limit {{ limit_kw | round(2) }} kW, margin {{ margin_kw | round(2) }} kW).
                  entity_id: sensor.ha1_peak_billable_power_kw
          - conditions:
              - condition: template
                value_template: "{{ flag_on and (load_kw < warning_kw - 0.3) and (margin_kw < -0.2) }}"
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.ha1_flag_peak_event_active
              - service: logbook.log
                data:
                  name: "HA1 Peak Guard"
                  message: >-
                    Task 20: Peak event cleared – {{ load_kw | round(2) }} kW back under warning (limit {{ limit_kw | round(2) }} kW).
                  entity_id: sensor.ha1_peak_billable_power_kw

  - id: ha1_batt_guard_min_soc_v13
    alias: "HA1 1.3 – Battery min-SOC guard"
    description: "Task 20 – Raise a debug flag when the Huawei battery SOC falls below the configured minimum and grid charge is allowed."
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.ha1_huawei_battery_soc
    condition:
      - condition: state
        entity_id: input_boolean.ha1_automations_master_enable
        state: 'on'
      - condition: state
        entity_id: input_boolean.ha1_control_battery_auto
        state: 'on'
      - condition: state
        entity_id: input_boolean.ha1_debug_freeze_optimizers
        state: 'off'
      - condition: template
        value_template: >-
          {{ states('sensor.ha1_huawei_battery_soc') not in ['unknown', 'unavailable', ''] }}
    action:
      - variables:
          soc: "{{ states('sensor.ha1_huawei_battery_soc') | float(0) }}"
          min_soc: "{{ states('input_number.ha1_battery_min_soc_normal') | float(0) }}"
          cutoff_soc: "{{ states('input_number.ha1_batt_grid_charge_cutoff_soc') | float(0) }}"
          allow_grid: "{{ is_state('input_boolean.ha1_battery_allow_grid_charge', 'on') }}"
          grid_flag: "{{ is_state('input_boolean.ha1_flag_battery_grid_charge_request', 'on') }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ allow_grid and soc < min_soc }}"
            sequence:
              - condition: template
                value_template: "{{ not grid_flag }}"
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.ha1_flag_battery_grid_charge_request
              - service: logbook.log
                data:
                  name: "HA1 Battery Guard"
                  message: >-
                    Task 20: Grid charge requested – SOC {{ soc | round(1) }}% below min {{ min_soc | round(1) }}% (cutoff {{ cutoff_soc | round(1) }}%).
                  entity_id: sensor.ha1_huawei_battery_soc
              # - service: script.ha1_batt_enable_grid_charge
              #   alias: "Future action: enable grid charge when guard trips"
          - conditions:
              - condition: template
                value_template: "{{ grid_flag and (not allow_grid or soc >= min_soc + 1 or (cutoff_soc > 0 and soc >= cutoff_soc)) }}"
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.ha1_flag_battery_grid_charge_request
              - service: logbook.log
                data:
                  name: "HA1 Battery Guard"
                  message: >-
                    Task 20: Grid charge flag cleared – SOC {{ soc | round(1) }}% back above guard band.
                  entity_id: sensor.ha1_huawei_battery_soc
              # - service: script.ha1_batt_disable_grid_charge
              #   alias: "Future action: disable forced grid charge when resolved"

  - id: ha1_batt_peak_reserve_flag_v13
    alias: "HA1 1.3 – Battery peak-reserve scaffold"
    description: "Task 20 – Track when peak events demand additional battery reserve for shaving."
    mode: single
    trigger:
      - platform: state
        entity_id:
          - sensor.ha1_huawei_battery_soc
          - input_boolean.ha1_flag_peak_event_active
          - input_number.ha1_batt_peak_shaving_soc
    condition:
      - condition: state
        entity_id: input_boolean.ha1_automations_master_enable
        state: 'on'
      - condition: state
        entity_id: input_boolean.ha1_control_battery_auto
        state: 'on'
      - condition: state
        entity_id: input_boolean.ha1_battery_peak_support_enabled
        state: 'on'
      - condition: state
        entity_id: input_boolean.ha1_debug_freeze_optimizers
        state: 'off'
    action:
      - variables:
          soc: "{{ states('sensor.ha1_huawei_battery_soc') | float(0) }}"
          target_soc: "{{ states('input_number.ha1_batt_peak_shaving_soc') | float(0) }}"
          peak_event: "{{ is_state('input_boolean.ha1_flag_peak_event_active', 'on') }}"
          reserve_flag: "{{ is_state('input_boolean.ha1_flag_battery_peak_reserve_needed', 'on') }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ peak_event and soc < target_soc }}"
            sequence:
              - condition: template
                value_template: "{{ not reserve_flag }}"
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.ha1_flag_battery_peak_reserve_needed
              - service: logbook.log
                data:
                  name: "HA1 Battery Guard"
                  message: >-
                    Task 20: Peak reserve needed – SOC {{ soc | round(1) }}% below peak target {{ target_soc | round(1) }}%.
                  entity_id: sensor.ha1_huawei_battery_soc
              # - service: script.ha1_batt_set_peak_shaving_mode
              #   alias: "Future action: enforce Huawei peak-shaving mode"
          - conditions:
              - condition: template
                value_template: "{{ reserve_flag and (not peak_event or soc >= target_soc + 1) }}"
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.ha1_flag_battery_peak_reserve_needed
              - service: logbook.log
                data:
                  name: "HA1 Battery Guard"
                  message: >-
                    Task 20: Peak reserve satisfied – SOC {{ soc | round(1) }}% meets target.
                  entity_id: sensor.ha1_huawei_battery_soc

  - id: ha1_ev_charge_window_planner_v13
    alias: "HA1 1.3 – EV charge window scaffold"
    description: "Task 20 – Determine safe/cheap charge windows based on price, peak margin, and VW time-left sensor."
    mode: single
    trigger:
      - platform: time_pattern
        minutes: "/15"
      - platform: state
        entity_id:
          - sensor.ha1_price_current
          - sensor.id4pro_charging_time_left
          - sensor.ha1_peak_margin_kw
    condition:
      - condition: state
        entity_id: input_boolean.ha1_automations_master_enable
        state: 'on'
      - condition: state
        entity_id: input_boolean.ha1_control_ev_auto
        state: 'on'
      - condition: state
        entity_id: input_boolean.ha1_debug_freeze_optimizers
        state: 'off'
    action:
      - variables:
          price_now: "{{ states('sensor.ha1_price_current') | float(0) }}"
          price_avg: "{{ states('sensor.ha1_price_today_avg') | float(0) }}"
          cheap_window: >-
            {% if price_avg | float(0) <= 0 %}
              {{ price_now > 0 }}
            {% else %}
              {{ price_now <= price_avg * 0.9 }}
            {% endif %}
          time_left_min: >-
            {% set raw = states('sensor.id4pro_charging_time_left') %}
            {% if raw in ['unknown', 'unavailable', 'none', '', None] %}
              0
            {% elif ':' in raw %}
              {% set parts = raw.split(':') %}
              {% if parts | length == 3 %}
                {% set hours = parts[0] | int(0) %}
                {% set minutes = parts[1] | int(0) %}
                {% set seconds = parts[2] | int(0) %}
                {{ hours * 60 + minutes + (seconds / 60) }}
              {% elif parts | length == 2 %}
                {% set hours = parts[0] | int(0) %}
                {% set minutes = parts[1] | int(0) %}
                {{ hours * 60 + minutes }}
              {% else %}
                0
              {% endif %}
            {% else %}
              {{ raw | float(0) }}
            {% endif %}
          peak_margin_kw: "{{ states('sensor.ha1_peak_margin_kw') | float(0) }}"
          obey_peak: "{{ is_state('input_boolean.ha1_ev_obey_peak_limit', 'on') }}"
          peak_blocked: "{{ is_state('input_boolean.ha1_flag_peak_event_active', 'on') }}"
          ev_flag: "{{ is_state('input_boolean.ha1_flag_ev_charge_window', 'on') }}"
          headroom_ok: "{{ (not obey_peak) or (peak_margin_kw <= -0.5) }}"
          should_charge: "{{ time_left_min > 0 and cheap_window and headroom_ok and (not peak_blocked) }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ should_charge }}"
            sequence:
              - condition: template
                value_template: "{{ not ev_flag }}"
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.ha1_flag_ev_charge_window
              - service: logbook.log
                data:
                  name: "HA1 EV Planner"
                  message: >-
                    Task 20: Charge window opened – {{ time_left_min | round(0) }} min needed, price {{ price_now | round(3) }} SEK/kWh (avg {{ price_avg | round(3) }}), margin {{ peak_margin_kw | round(2) }} kW.
                  entity_id: sensor.id4pro_charging_time_left
              # - service: script.ha1_ev_start_charging
              #   alias: "Future action: start Easee charging when safe"
          - conditions:
              - condition: template
                value_template: "{{ ev_flag and (not should_charge) }}"
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.ha1_flag_ev_charge_window
              - service: logbook.log
                data:
                  name: "HA1 EV Planner"
                  message: >-
                    Task 20: Charge window closed – guard failed (cheap={{ cheap_window }}, headroom={{ headroom_ok }}, peak_blocked={{ peak_blocked }}).
                  entity_id: sensor.id4pro_charging_time_left

  - id: ha1_ev_peak_block_flag_v13
    alias: "HA1 1.3 – EV peak block scaffold"
    description: "Task 20 – Highlight when EV charging should pause during a peak event."
    mode: single
    trigger:
      - platform: state
        entity_id:
          - input_boolean.ha1_flag_peak_event_active
          - binary_sensor.ev_is_charging
    condition:
      - condition: state
        entity_id: input_boolean.ha1_automations_master_enable
        state: 'on'
      - condition: state
        entity_id: input_boolean.ha1_control_ev_auto
        state: 'on'
      - condition: state
        entity_id: input_boolean.ha1_ev_obey_peak_limit
        state: 'on'
    action:
      - variables:
          peak_event: "{{ is_state('input_boolean.ha1_flag_peak_event_active', 'on') }}"
          ev_charging: "{{ is_state('binary_sensor.ev_is_charging', 'on') }}"
          flag_on: "{{ is_state('input_boolean.ha1_flag_ev_peak_block', 'on') }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ peak_event and ev_charging }}"
            sequence:
              - condition: template
                value_template: "{{ not flag_on }}"
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.ha1_flag_ev_peak_block
              - service: logbook.log
                data:
                  name: "HA1 EV Peak Guard"
                  message: "Task 20: EV charging should pause – active peak event and charger drawing power."
                  entity_id: binary_sensor.ev_is_charging
              # - service: script.ha1_ev_stop_charging
              #   alias: "Future action: pause Easee charging"
          - conditions:
              - condition: template
                value_template: "{{ flag_on and (not peak_event or not ev_charging) }}"
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.ha1_flag_ev_peak_block
              - service: logbook.log
                data:
                  name: "HA1 EV Peak Guard"
                  message: "Task 20: EV peak block cleared – no longer charging during an active peak."
                  entity_id: binary_sensor.ev_is_charging
              # - service: script.ha1_ev_resume_charging
              #   alias: "Future action: resume Easee charging"
