# --- HomeAssistant 1.3 – Comfort Override Automations (Phase 1) ---
# Handles:
# - Global comfort override ON/OFF
# - Timer-based auto-expiration
# - Logbook visibility

automation:

  # ---------------------------------------------------------------------------
  # Comfort override turned ON
  # ---------------------------------------------------------------------------
  - id: ha1_comfort_override_on
    alias: "HA1 – Comfort override ON"
    description: >
      Starts the comfort override timer and logs that comfort override
      is enabled. Comfort override allows EV and battery to relax price/peak
      optimization, but master + safety rails still apply.
    triggers:
      - trigger: state
        entity_id: input_boolean.ha1_comfort_override_enabled
        from: "off"
        to: "on"
    conditions:
      - condition: state
        entity_id: input_boolean.ha1_automations_master_enable
        state: "on"
    actions:
      # Start timer with duration based on input_number.ha1_comfort_override_duration_hours
      - action: timer.start
        target:
          entity_id: timer.ha1_comfort_override
        data:
          duration: >
            {% set raw = states("input_number.ha1_comfort_override_duration_hours") | int(4) %}
            {% set hours = 1 if raw < 1 else raw %}
            {{ "%02d:00:00" | format(hours) }}

      # Log to logbook
      - action: logbook.log
        data:
          name: "HA1 – Comfort override"
          entity_id: input_boolean.ha1_comfort_override_enabled
          message: >
            Comfort override ENABLED – price/peak limits may be relaxed.
          domain: automation

    mode: single

  # ---------------------------------------------------------------------------
  # Comfort override turned OFF manually
  # ---------------------------------------------------------------------------
  - id: ha1_comfort_override_off
    alias: "HA1 – Comfort override OFF"
    description: >
      Cancels the comfort override timer and logs that comfort override
      is disabled. Normal optimization rules apply again.
    triggers:
      - trigger: state
        entity_id: input_boolean.ha1_comfort_override_enabled
        from: "on"
        to: "off"
    conditions:
      - condition: state
        entity_id: input_boolean.ha1_automations_master_enable
        state: "on"
    actions:
      # Cancel timer (if running)
      - action: timer.cancel
        target:
          entity_id: timer.ha1_comfort_override

      # Log to logbook
      - action: logbook.log
        data:
          name: "HA1 – Comfort override"
          entity_id: input_boolean.ha1_comfort_override_enabled
          message: >
            Comfort override DISABLED – back to normal optimization.
          domain: automation

    mode: single

  # ---------------------------------------------------------------------------
  # Comfort override timer finished → auto-expire override
  # ---------------------------------------------------------------------------
  - id: ha1_comfort_override_auto_expire
    alias: "HA1 – Comfort override auto-expire"
    description: >
      When the comfort override timer finishes, automatically turn off
      the comfort override (if still on) and log the auto-expiration.
    triggers:
      - trigger: event
        event_type: timer.finished
        event_data:
          entity_id: timer.ha1_comfort_override
    conditions:
      - condition: state
        entity_id: input_boolean.ha1_automations_master_enable
        state: "on"
      - condition: state
        entity_id: input_boolean.ha1_comfort_override_enabled
        state: "on"
    actions:
      # Turn off comfort override
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.ha1_comfort_override_enabled

      # Log to logbook
      - action: logbook.log
        data:
          name: "HA1 – Comfort override"
          entity_id: input_boolean.ha1_comfort_override_enabled
          message: >
            Comfort override AUTO-EXPIRED – timer reached
            {{ states("input_number.ha1_comfort_override_duration_hours") | int(4) }}h.
          domain: automation

    mode: single
