###############################################################################
# HomeAssistant 1.3 – Comfort Override Automations (Phase 1)
# Scope:
#   - Time-boxed comfort overrides (visible + logged)
#   - Temporary relaxation of price/peak guardrails
#   - Simple cleanup/reset to return to optimized behavior
###############################################################################

automation:

  # ---------------------------------------------------------------------------
  # Comfort override: enable/extend with expiry
  # ---------------------------------------------------------------------------
  - id: ha1_comfort_override_enable
    alias: "HA1 – Comfort override: enable/extend"
    mode: single
    trigger:
      - platform: state
        entity_id: input_boolean.ha1_comfort_override_enabled
        to: "on"
    condition: []
    action:
      - variables:
          raw_hours: "{{ states('input_number.ha1_comfort_override_duration_hours') | float(2) }}"
          duration_hours: "{{ [raw_hours, 0.5] | max }}"
          until_ts: "{{ now().timestamp() + (duration_hours * 3600) }}"
          until_dt: "{{ as_datetime(until_ts) | as_local }}"
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.ha1_comfort_override_until
        data:
          date: "{{ until_dt.strftime('%Y-%m-%d') }}"
          time: "{{ until_dt.strftime('%H:%M:%S') }}"

      # Relax guardrails that are safe to override temporarily.
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.ha1_allow_high_price_heating
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.ha1_ev_obey_peak_limit

      - service: logbook.log
        data:
          name: "HA1 Comfort"
          message: >
            Comfort override enabled for {{ duration_hours | round(1) }}h
            (until {{ until_dt.strftime('%Y-%m-%d %H:%M') }}).
            Peak/price guardrails relaxed for heating and EV.
          entity_id: input_boolean.ha1_comfort_override_enabled

  # ---------------------------------------------------------------------------
  # Comfort override: auto-expire when the "until" timestamp passes
  # ---------------------------------------------------------------------------
  - id: ha1_comfort_override_expire
    alias: "HA1 – Comfort override: auto-expire"
    mode: single
    trigger:
      - platform: template
        value_template: >
          {% set enabled = is_state('input_boolean.ha1_comfort_override_enabled', 'on') %}
          {% set until_ts = as_timestamp(states('input_datetime.ha1_comfort_override_until')) %}
          {{ enabled and until_ts is not none and until_ts > 0 and now().timestamp() >= until_ts }}
    condition: []
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.ha1_comfort_override_enabled

  # ---------------------------------------------------------------------------
  # Comfort override: cleanup + reset when disabled (manual or expired)
  # ---------------------------------------------------------------------------
  - id: ha1_comfort_override_cleanup
    alias: "HA1 – Comfort override: cleanup/reset"
    mode: single
    trigger:
      - platform: state
        entity_id: input_boolean.ha1_comfort_override_enabled
        from: "on"
        to: "off"
    condition: []
    action:
      - variables:
          until_ts: "{{ as_timestamp(states('input_datetime.ha1_comfort_override_until')) }}"
          expired: >
            {% set valid_until = until_ts is not none and until_ts > 0 %}
            {{ valid_until and now().timestamp() >= until_ts }}

      # Restore optimized defaults.
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.ha1_allow_high_price_heating
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.ha1_ev_obey_peak_limit

      - service: logbook.log
        data:
          name: "HA1 Comfort"
          message: >
            Comfort override {{ 'expired' if expired else 'disabled manually' }};
            optimized price/peak behavior restored.
          entity_id: input_boolean.ha1_comfort_override_enabled
