###############################################################################
# Package: nordpool_cheapest_hours.yaml
# Purpose:
#   - Calculate the sequential cheapest Nordpool hours for tomorrow
#   - Store start/end helpers that downstream automations can reference
#   - Reset the booking flag each night so calendars can reschedule
###############################################################################

sensor:
  - platform: template
    sensors:
      cheapest_hours_energy_tomorrow:
        device_class: timestamp
        friendly_name: Cheapest sequential electricity hours
        # Example configuration calculates six cheapest hours for the full next day (00:00–24:00)
        # CHANGE-ME: numberOfSequentialHours = Number of sequential cheapest hours we are looking for
        # CHANGE-ME: lastHour = Final hour to search (start of final hour, e.g. 23 => 23:00-24:00)
        # CHANGE-ME: firstHour = First hour to search from
        # CHANGE-ME: Update the Nordpool entity id below (TWO ENTRIES): sensor.nordpool_kwh_se3_sek_2_095_025
        value_template: >
          {%- set numberOfSequentialHours = 6 -%}
          {%- set lastHour = 23 -%}
          {%- set firstHour = 0 -%}
          {%- if state_attr('sensor.nordpool_kwh_se3_sek_2_095_025', 'tomorrow_valid') == true -%}
            {%- set ns = namespace(counter=0, list=[], cheapestHour=today_at("00:00") + timedelta(hours=24), cheapestPrice=999.00) -%}
            {%- for i in range(firstHour + numberOfSequentialHours, lastHour + 1) -%}
              {%- set ns.counter = 0.0 -%}
              {%- for j in range(i - numberOfSequentialHours, i) -%}
                {%- set ns.counter = ns.counter + state_attr('sensor.nordpool_kwh_se3_sek_2_095_025', 'tomorrow')[j] -%}
              {%- endfor -%}
              {%- set ns.list = ns.list + [ns.counter] -%}
              {%- if ns.counter < ns.cheapestPrice -%}
                {%- set ns.cheapestPrice = ns.counter -%}
                {%- set ns.cheapestHour = today_at("00:00") + timedelta(hours=(24 + i - numberOfSequentialHours)) -%}
              {%- endif -%}
            {%- endfor -%}
            {{ ns.cheapestHour }}
            {%- set ns.cheapestPrice = ns.cheapestPrice / numberOfSequentialHours -%}
          {%- endif -%}

# Helpers to keep the start / end time
input_datetime:
  device_start_time:
    name: Device Start Time
    has_time: true
    has_date: false
  device_end_time:
    name: Device End Time
    has_time: true
    has_date: false

# Shared helper – target SoC when charging battery during cheapest hours
input_number:
  battery_cheapest_hours_target_soc:
    name: "Battery target SoC during cheapest hours"
    min: 20
    max: 100
    step: 5
    unit_of_measurement: "%"
    icon: mdi:battery-charging-80

# Automations
automation:
  - id: '1663398489322'
    alias: 'Set device/end start time'
    description: ''
    trigger:
      - platform: time
        at: '23:15:00'
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.cheapest_hours_energy_tomorrow
            state: unknown
    action:
      - service: input_datetime.set_datetime
        data:
          time: "{{ as_timestamp(states('sensor.cheapest_hours_energy_tomorrow')) | timestamp_custom('%H:%M') }}"
        target:
          entity_id: input_datetime.device_start_time
      - service: input_datetime.set_datetime
        data:
          # CHANGE-ME: 6 (3600*6) is the number of sequential cheapest hours we are looking for
          time: "{{ (as_timestamp(states('sensor.cheapest_hours_energy_tomorrow')) + (3600 * 6)) | timestamp_custom('%H:%M') }}"
        target:
          entity_id: input_datetime.device_end_time
    mode: single

  # CHANGE-ME: Do anything you like when the start / stop triggers hit.
  # Start the device for cheapest hours
  - id: '1663399614858'
    alias: Turn on device for cheapest hours
    description: ''
    trigger:
      - platform: time
        at: input_datetime.device_start_time
    condition: []
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.cheap_electricity_simulated_switch
    mode: single

  # Stop the device after cheapest hours
  - id: '1663399614818'
    alias: Turn off device after cheapest hours
    description: ''
    trigger:
      - platform: time
        at: input_datetime.device_end_time
    condition: []
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.cheap_electricity_simulated_switch
    mode: single

  ###########################################################################
  # Reset flag each night so new cheapest windows can be booked
  ###########################################################################
  - alias: 'Nordpool – reset cheapest hours flag daily'
    id: nordpool_reset_cheapest_hours_flag_daily
    mode: single
    trigger:
      - platform: time
        at: '00:10:00'
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.cheapest_hours_set
