###############################################################################
# Package: nordpool_cheapest_hours.yaml
# Purpose:
#   Tie Nordpool "cheapest hours" sensors to calendar.electricity
#   - Uses:
#       sensor.cheapest_hours_energy_1
#       sensor.cheapest_hours_energy_2
#       input_boolean.cheapest_hours_set
#       calendar.electricity
###############################################################################

###############################################################################
# 1. Input boolean – mark if cheapest hours already scheduled
###############################################################################
#input_boolean:
#  cheapest_hours_set:
#    name: "Cheapest hours scheduled"
#    icon: mdi:calendar-clock

###############################################################################
# 2. Automation – Create calendar event for cheapest hours
#
# Assumptions:
#   - sensor.cheapest_hours_energy_1 and _2 have:
#       state: start timestamp (ISO-format)
#       attribute 'duration' (hours) for how long perioden är
#
#   Justera attribut-namnet om din integration använder något annat
#   (t.ex. 'duration_hours', 'hours', etc).
###############################################################################
automation:

  ###########################################################################
  # 3. Automation – Reset flag each night
  #    Så att nya billigaste fönster kan bokas nästa dygn.
  ###########################################################################
  - alias: "Nordpool – reset cheapest hours flag daily"
    id: nordpool_reset_cheapest_hours_flag_daily
    mode: single
    trigger:
      - platform: time
        at: "00:10:00"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.cheapest_hours_set
