###############################################################################
# Package: weather_energy.yaml
# Purpose:
#   Wind Energy Correlation (Forecast Sensor Logic)
#   - Fetches German wind forecast (Open-Meteo, Berlin proxy)
#   - Builds 24h statistics for wind speed
#   - Computes a "wind → price impact" correlation index
#   - Logs an observed correlation between wind index and Nordpool price
###############################################################################

###############################################################################
# 1. REST – Fetch German wind forecast (Open-Meteo, Berlin / Germany proxy)
###############################################################################
rest:
  - resource: https://api.open-meteo.com/v1/forecast
    method: GET
    params:
      latitude: 52.52          # Berlin latitude
      longitude: 13.41         # Berlin longitude
      hourly: wind_speed_10m
      timezone: Europe/Berlin
    scan_interval: 3600        # Update every hour
    timeout: 30
    sensor:
      - name: "Germany Forecast Wind"
        unique_id: germany_forecast_wind
        value_template: >
          {% set data = value_json.get('hourly', {}).get('wind_speed_10m', []) %}
          {% if data and data[0] is not none %}
            {{ data[0] }}
          {% else %}
            unknown
          {% endif %}
        unit_of_measurement: "m/s"
        device_class: wind_speed
        state_class: measurement

###############################################################################
# 2. Statistics – 24h rolling stats for German wind speed
#    (Uses sensor platform "statistics" instead of top-level `statistics:`)
###############################################################################
sensor:
  - platform: statistics
    name: "Germany Forecast Wind 24h Stats"
    unique_id: germany_forecast_wind_24h_stats
    entity_id: sensor.germany_forecast_wind
    state_characteristic: mean
    max_age:
      hours: 24

###############################################################################
# 3. Template sensors – Correlation logic used by the rulebook
###############################################################################
template:
  - sensor:
      #########################################################################
      # sensor.wind_average_24h
      # - Rolling 24h mean from the statistics sensor above
      #########################################################################
      - name: "Wind Average 24h"
        unique_id: wind_average_24h
        unit_of_measurement: "m/s"
        device_class: wind_speed
        state_class: measurement
        state: >
          {{ state_attr('sensor.germany_forecast_wind_24h_stats', 'mean') | float(0) }}

      #########################################################################
      # sensor.wind_energy_correlation_index
      # - Estimated price impact based on wind (matches documentation)
      #   > 8  m/s  → ≈ -10 % price impact
      #   5–8 m/s   → ≈ -5 % price impact
      #   < 5  m/s  → 0 %
      #########################################################################
      - name: "Wind Energy Correlation Index"
        unique_id: wind_energy_correlation_index
        unit_of_measurement: "%"
        icon: mdi:weather-windy
        state_class: measurement
        state: >
          {% set w = states('sensor.wind_average_24h') | float(0) %}
          {% if w > 8 %}
            -10
          {% elif w >= 5 %}
            -5
          {% else %}
            0
          {% endif %}

      #########################################################################
      # sensor.wind_price_correlation_observed
      # - Observed correlation between wind index and Nordpool prices
      # - Simple heuristic:
      #   * Compare current price vs its own "average" attribute (if available)
      #   * Combine that with the wind correlation index as a sanity check
      #
      #   This is a first version and can be refined later if we want
      #   a more analytical correlation (e.g. using long term history).
      #########################################################################
      - name: "Wind Price Correlation Observed"
        unique_id: wind_price_correlation_observed
        unit_of_measurement: "%"
        icon: mdi:chart-line
        state_class: measurement
        state: >
          {% set price = states('sensor.nordpool_kwh_se3_sek_2_095_025') | float(0) %}
          {% set wind_idx = states('sensor.wind_energy_correlation_index') | float(0) %}
          {% set avg = state_attr('sensor.nordpool_kwh_se3_sek_2_095_025',
                                  'average') | default(price, true) | float(0) %}
          {% if avg == 0 %}
            0
          {% else %}
            {{ (((price - avg) / avg) * 100) | round(1) + wind_idx }}
          {% endif %}
